### ISSUE TITLE
Add non-Arena sets

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#106]
Several responses in Survey #1 and messages in Discord have asked about supporting sets with cards that aren't in Arena. Using this issue to track that, although the current developer(s) might not have a lot of interest in this or ability to test it. That said, I think this makes sense as a question in Survey #2.

**Comment by Senryoku** [comment]
Obviously opening the app to non-Arena users would be cool.
Here's what's preventing me to start working on that:
- Arena IDs are used as unique ID for cards internally, we'd have to change to another ID set. This is fixable, and probably desirable even if we don't introduce non-Arena cards (helps supporting incoming sets earlier, handle some duplicate within the Arena DB...), but it's still a scary change.
- DB Size. Right now all card data is just loaded on startup. We'd have to load additional "vintage data" on demand (probably too large), or re-think how to supply card data entirely (full card objects in every message instead of just an ID?). 
- I expect a lot of corner cases with older cards, but I may be worrying for nothing.
- It's just a lot more to test, and I'm already missing a lot of regressions all the time :D
