### ISSUE TITLE
Auto-firing pod queues

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#117]
This is an enhancement we can survey for interest on Survey 2. If usage and interest supports this, we could have a way for players to queue for a default draft of the current set, and then automatic creation of 8-player drafts once enough users have queued. Along with this we may want some basic community guidelines around timeliness in playing games after the draft, a way to track Arena handles, and the ability to volunteer as a non-player owner ("judge") that verifies results and expedites match setup for new players. Plenty of decisions and unknowns here, but worth seeing how much interest there is.

**Comment by Senryoku** [comment]
Automatic matchmaking is interesting, but I feel like that's out of the scope of the application. We'd have to add a better and persistent chat, some way to indicate user preferences and probably a lot of things that I'm not immediately thinking about.

Someone already asked me about an API to create and manage sessions programmatically for a Discord Bot. I wasn't comfortable building such an API since I don't have experience with that (especially with authorization/authentication) but if we had one we could leverage the Discord server to let player organize and help them with a bot.

**Comment by tooomm** [comment]
With something like that there comes a lot more! How do you assure quality of games, etiquette and penalties etc.?

I don't think that should all be part of the site unless you want to build up your own community and manage + moderate it... currently plenty of discord groups and private playgroups handle that nicely.

The bot idea on the other hand could even strengthen those already existing communities and makes the experience more seamless.
