### ISSUE TITLE
Deck sharing: custom columns

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#146]
Enhancement request for deck sharing. If a user moves or sorts cards between columns before sharing, we should maintain that in the shared version of the deck.

**Comment by tooomm** [comment]
To me, this sounds like a niche feature with potential downside even.
Different users have different personal preferences - their own style - in how they lay their deck out. Why force others to see a deck their way? One might order by function of a card, others go by good old type. Some put all non-creates in one pile, or have a maybe pile and so on.

Users can freely rearrange cards in columns already when viewing them in logs or the bracket.

As long as their is a known standard on how decks are displayed by default for everybody, the viewer can go from there and adjust as he likes.
If the deck view of a shared deck looks different all the time because it is shown in the way a different person likes it most - you have to understand the logic behind that first before adjusting it to your needs.

**Comment by wrmacrae** [comment]
I see your point about different people sorting differently, that's definitely true. But I somewhat disagree about the downside, because there's still a button to sort everything by CMC, so if someone disagree with the current columns they can click that and get back to current performance. Does the one-click option to sort by CMC and restore default columns change your mind, @tooomm ?

I think some column-setting approaches are more niche (like putting tricks and removal in their own column, or moving MDFCs with lands to count colored sources more easily). But other things I suspect would have consensus among most players: split cards probably go into the column of the cost you're most likely to use, Roost of Drakes is a 4 drop, Stonecoil Serpent isn't a 0-drop, etc.

Overall, I suspect deck sharing has two primary uses. One is for simulating open decklists before playing matches; in that case this feature is less important, since it'll be on opponents to evaluate your deck the best they can. But the other is reviewing the rest of the pod for learning purposes, either after playing matches or in lieu of matches (e.g. when testing a new set before release or testing team draft strategies); even potentially doing "deck techs" for each other. For this one, saving others time in reviewing your work is a pretty convenient addition, I think.

**Comment by Senryoku** [comment]
I see the point for learning, but like @tooomm I still think this is really niche feature. I'm not a fan of tying the log format to its presentation just for that, especially when there's still discussion on how to improve the CardPool component (#145).

**Comment by tooomm** [comment]
True, sorting back to e.g. CMC is not a big deal.
It should be it's own sorting option to switch between for sure. It also doesn't have to be the default view necessarily.

Maybe something for later. 👍

**Comment by Senryoku** [comment]
Closing this one as I'm not personally in favor of implementing it.
