### ISSUE TITLE
Handle column wrapping for deck better

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#155]
Some discussion in #145 but this deserves its own issue, and is probably more important than a lot of the related issues: some users have a small enough resolution that the default deck columns don't fit horizontally, so the highest CMC wraps to a new row and requires vertical scrolling. I think this may have started when the sideboard gave an option for being on the side vs the bottom. A handful of things that might help with this (some are worth experimenting with first and could actually be worse):
- lower the default or maximum number of columns, possibly also binning 0 and 1 CMC together
- start the sideboard on the bottom instead of the side
- reduce the width of columns (always)
- reduce the width of columns dynamically when there are too many columns to fit in one row
- use horizontal scrolling instead of wrapping

**Comment by tooomm** [comment]
>most users have a small enough resolution that the default deck columns don't fit horizontally

Not sure if that's really the case. On Full HD resolution I can see the default 7 columns + the sideboard on the right perfectly fine next to each other. I doubt that most users use anything lower than that.

However this is still an issue and users want/need more columns sometimes, or some are limited to like older 1600*900 resolution screens etc.

If the dynamic width adjustment works out, that sounds promising.

**Comment by Senryoku** [comment]
I've always optimized for a Full HD display, partly because it's what I was working with, but I'm also guessing it's a good portion of the user base. I tried to keep it usable with lower resolution (like 1280x720).

Some new experimentation (scaling) there:  #160
 
I finally managed to get horizontal scrolling working on a local branch (pretty easy to do from #160), but it's probably not worth pursuing (just moving the scrollbar to the top of the container - where it should be in this case - is a pain)

**Comment by tooomm** [comment]
>Some new experimentation (scaling) there: #160

I tested it on 1920x1080, 1366x768 and on a 7" tablet - usable on all. And a huge improvement.
Before, I was basically not able to build a deck on 1366x768 as several columns wrapped already and I could barely see them all at once on the small laptop screen.

**Comment by wrmacrae** [comment]
https://github.com/Senryoku/MTGADraft/pull/160
