### ISSUE TITLE
Spectator mode, or see draft logs/replay via link

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#198]
It would be great to be able to view a draft as it's happening as an observer. An alternative that might be a bit easier but captures a lot of the value would be link-sharing of draft logs or draft replays; not quite as good because you can't view things live, but the interface would be much simpler.

**Comment by Senryoku** [comment]
I guess we could re-use the "DraftLogLive" component pretty much unchanged (aside from some needed UI improvement)
Some concerns that come to mind:
 - Spectator links should not divulge the session ID, we'd have to generate an a random alias for each session (only on the owner request?)
 - Current implementation of the Live feature assumed a single spectator, we'd have to review the bandwidth usage.
 - Server side tasks:
   - Allow another type of websocket connection? (If the spectator page is separate and not part of the main app, like read-only brackets)
   - Adding server-side support for multiple "subscribers" to events (broadcast via these sockets).

**Comment by wrmacrae** [comment]
Regarding session ID, I'd say that 95% of the time the session ID becomes obvious because of a URL being linked or streamed, and users are depending on first-come-first-serve, or just booting people as necessary. A workaround would be to hold off on spectator link until all the players are in the pod. But I agree that a random alias would be an improvement to defend against cases where people didn't fill up their pod first.
Great point about server load. Especially since I think this would get most usage in drafts with high viewership. If you had authentication and a Patreon you could actually paywall this kind of thing or the beta of this (that what 17lands does with new features that have perf concerns). In the shorter term, maybe just start with a cap on spectators too so that you can observe usage without dumpstering performance.

**Comment by Senryoku** [comment]
I started working on this, but realized a fatal flaw that somehow didn't occur to me until then: There's nothing preventing players to access this spectator view. And limiting it in any way just comes back to having an organizer.

I'm now sure it's worth the maintenance burden if it ends up never being used by fear of cheating (especially since it would be mainly useful for tournaments). Improving the existing live view for organizer is probably a better investment, but I'd like to have some feedback from tournament organizers (I've actually never seen it used in the wild).
