### ISSUE TITLE
STX lessons shouldn't adjust rarity targets

### ISSUE THREAD

**Issue by wrmacrae** [Senryoku/MTGADraft#237]
This code makes it so that a Strixhaven rare lesson takes the place of the normal rare in a pack: https://github.com/Senryoku/MTGADraft/blob/master/src/BoosterFactory.js#L439

But unlike with analogous slots in other sets (legendaries n DOM, planeswalkers in WAR, MDFCs in ZNR, etc.) the lessons do not replace the rare if they show up at rare/mythic. See the Draft Boosters section here: https://magic.wizards.com/en/articles/archive/feature/strixhaven-school-mages-product-overview-2021-03-25

**Comment by wrmacrae** [comment]
I'm working on a fix for this, and may also roll in mystical archive rarity distribution (67% uncommon, 26.4% rare, 6.6% mythic) according to https://magic.wizards.com/en/articles/archive/feature/collecting-strixhaven-school-mages-2021-03-25

**Comment by Senryoku** [comment]
Sorry I started fixing this before your comment, the lesson issue should be fixed with 15dff7f26e7db17235ce9803ab3607211df745e6 and 56b521b4a37cd14baefd4c3e3bad0dd12b3895b9 (this still updates the targets but always replaces a common, this way I don't have to manually adjust default targets for STX).

**Comment by wrmacrae** [comment]
nice! I can close this out, then, thanks! I'm still looking for rarity distribution of lessons, but it shouldn't be hard to reweight the STA rarities for now at least.
