### ISSUE TITLE
Add a MTGO-compatible export format

### ISSUE THREAD

**Issue by nex3** [Senryoku/MTGADraft#346]
Currently, you can export a decklist in plain text or Arena format. It would be really nice to have an option to export it in MTGO format. Although it can _mostly_ consume the plain text format, there are a few situations where these formats differ (MTGO, for example, expects split cards to be `A/B` rather than `A // B`). In an _ideal_ world, you'd be able to download a `.dek` format which would include the correct _versions_ of each card as well... but I think this would require having a little bit more Scryfall data on hand than is currently available.

Due to the nature of MTGO cubing where one player typically has the entire cube in their account and using other players' decklists to trade, it would also be nice if these decklists didn't include basic lands.

I may be able to find some time to work on this myself at some point.

**Comment by Senryoku** [comment]
Exporting to the .dek format should be doable (see #347). 
I don't use MTGO myself, but after some quick testing it seems pretty lax about the `Name` field,  but outright crashes if `CatID` is missing. It seems pretty reasonable to make some requests to Scryfall to get the MTGO ids, so I went with that.

Not sure what to do about the basics, in the case of a regular set draft I guess the user would expect the MTGO export to behave like the other options. Should I allow turning off the completion to 40 cards with basics, rather than make the MTGO export a special case?

Note: The retro artifacts from The Brothers' War do not have a MTGO id in the Scryfall DB (yet?).

**Comment by nex3** [comment]
> Should I allow turning off the completion to 40 cards with basics, rather than make the MTGO export a special case?

Making this configurable per-draft would also work, especially if that persists across sessions.

**Comment by Senryoku** [comment]
I realized you can already set the `Deck Size` to 0 to quickly get the same behavior, this is a little obtuse but may be enough for what's I think is a fringe use case? I'm a little hesitant to add yet another checkbox in this dropdown.

Other than that I think I'm done with my PR #347 for now if you want to give it a try.

**Comment by nex3** [comment]
> I realized you can already set the `Deck Size` to 0 to quickly get the same behavior, this is a little obtuse but may be enough for what I think is a fringe use case? I'm a little hesitant to add yet another checkbox in this dropdown.

The problem is I'd like to avoid having to teach each of my drafters to do it individually, so having a way to set it for the whole draft would be really valuable.

> Other than that I think I'm done with my PR https://github.com/Senryoku/MTGADraft/pull/347 for now if you want to give it a try.

Is there a good way to run a draft against this, or do I need to build it locally?

**Comment by Senryoku** [comment]
> > I realized you can already set the `Deck Size` to 0 to quickly get the same behavior, this is a little obtuse but may be enough for what I think is a fringe use case? I'm a little hesitant to add yet another checkbox in this dropdown.
> 
> The problem is I'd like to avoid having to teach each of my drafters to do it individually, so having a way to set it for the whole draft would be really valuable.

Ah, I see. These settings are client side only right now and I'd rather keep it that way. 
If you don't mind trading more cards than absolutely necessary, perhaps you can try exporting the raw list of drafted cards from the draft log yourself instead of asking each player to share their deck list?

> > Other than that I think I'm done with my PR #347 for now if you want to give it a try.
> 
> Is there a good way to run a draft against this, or do I need to build it locally?

Sadly I can't spin up instances for each PR anymore, you'll have to build it locally :(

**Comment by Senryoku** [comment]
PR merged and deployed. You can test it on the main instance.
Closing this issue, please open a new one if you find any problem when you get the chance to try it.
