### ISSUE TITLE
Drop down interaction

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#380]
The dropdown menu is not closed when the mouse leaves the initial element containing the menu:
![dropdown](https://user-images.githubusercontent.com/9874850/221409469-17b75c04-aa33-4bbd-be76-65e33a5e9cc0.png)

**Comment by Senryoku** [comment]
This is surprisingly hard to fix properly. I tried multiple approaches, but all of them have some drawbacks. 

Firstly we have to react to the dropdown closing: I'm currently using the `:hover` css pseudo-element on desktop and it turns out that the behavior of js mouseenter/mouseleave events does not perfectly match. I re-wrote the Dropdown component to use js events instead to avoid some pitfalls there.
Next, we need to close `<select>` dropdowns on mouseleave: emiting a `blur` event works great!... On Firefox. There's no clean way to do this in Chrome afaik. That's pretty much a dead end in Chrome apart from some really hackish ways to hide (not close) the dropdown.
Then I realized that hovering the `<select>` dropdown will trigger a `mouseleave` event on Firefox, closing it immediately because of our previous 'fix' and making it unusable. I can filter these events, but then we re-open some edge cases where the dropdown won't close properly.

As I didn't find a proper way to fix it and it's a really minor annoyance, I'll close this as won't fix for now.
